export const MODULES = [
  { slug: 'welcome',          number: '00', title: 'Welcome' },
  { slug: 'brand-foundation', number: '01', title: 'Brand Foundation' },
  { slug: 'visual-world',     number: '02', title: 'Visual World' },
  { slug: 'content',          number: '03', title: 'Create Content' },
  { slug: 'launch',           number: '04', title: 'Launch' },
  { slug: 'playbook',         number: '05', title: 'The Playbook' },
] as const

export type ModuleSlug = typeof MODULES[number]['slug']

export interface SectionDef {
  slug: string
  name: string
  fields: { key: string; required: boolean }[]
}

// MODULE_SECTIONS defines section slugs and names for all workshop modules.
// Field arrays are populated by each module plan (02-05) when section components are built.
// welcome and playbook are excluded — they have no sub-sections.
export const MODULE_SECTIONS: Partial<Record<ModuleSlug, SectionDef[]>> = {
  'brand-foundation': [
    { slug: 'overview',        name: 'Overview',        fields: [] },
    { slug: 'brand-journey',   name: 'Brand Journey',   fields: [
      { key: 'bf_journey_outcome',   required: true },
      { key: 'bf_journey_why',       required: true },
      { key: 'bf_journey_known',     required: true },
      { key: 'bf_journey_do',        required: true },
      { key: 'bf_journey_learn',     required: true },
      { key: 'bf_journey_statement', required: false },
    ]},
    { slug: 'avatar',          name: 'Avatar',          fields: [
      { key: 'bf_av1_age',        required: false },
      { key: 'bf_av1_gender',     required: false },
      { key: 'bf_av1_occupation', required: false },
      { key: 'bf_av1_income',     required: false },
      { key: 'bf_av1_situation',  required: true },
      { key: 'bf_av1_who',        required: true },
      { key: 'bf_av1_look',       required: false },
      { key: 'bf_av1_story',      required: true },
      { key: 'bf_av1_goals',      required: true },
      { key: 'bf_av1_passions',   required: false },
      { key: 'bf_av1_struggle',   required: true },
      { key: 'bf_av1_tried',      required: false },
      { key: 'bf_av1_desired',    required: true },
      { key: 'bf_av1_fears',      required: false },
      { key: 'bf_av1_platforms',  required: false },
      { key: 'bf_av1_connection', required: false },
      { key: 'bf_av1_statement',  required: false },
      { key: 'bf_av2_age',        required: false },
      { key: 'bf_av2_gender',     required: false },
      { key: 'bf_av2_occupation', required: false },
      { key: 'bf_av2_income',     required: false },
      { key: 'bf_av2_situation',  required: false },
      { key: 'bf_av2_who',        required: false },
      { key: 'bf_av2_look',       required: false },
      { key: 'bf_av2_story',      required: false },
      { key: 'bf_av2_goals',      required: false },
      { key: 'bf_av2_passions',   required: false },
      { key: 'bf_av2_struggle',   required: false },
      { key: 'bf_av2_tried',      required: false },
      { key: 'bf_av2_desired',    required: false },
      { key: 'bf_av2_fears',      required: false },
      { key: 'bf_av2_platforms',  required: false },
      { key: 'bf_av2_connection', required: false },
      { key: 'bf_av2_statement',  required: false },
    ]},
    { slug: 'core-mission',    name: 'Core Mission',    fields: [
      { key: 'bf_ikigai_love',    required: true },
      { key: 'bf_ikigai_good',    required: true },
      { key: 'bf_ikigai_world',   required: true },
      { key: 'bf_ikigai_paid',    required: true },
      { key: 'bf_ikigai_center',  required: false },
      { key: 'bf_mission_avatar', required: true },
      { key: 'bf_mission_outcome',required: true },
      { key: 'bf_mission_method', required: true },
      { key: 'bf_mission_why',    required: true },
      { key: 'bf_core_mission',   required: false },
    ]},
    { slug: 'core-values',     name: 'Core Values',     fields: [
      { key: 'bf_val1_name',     required: false },
      { key: 'bf_val1_practice', required: false },
      { key: 'bf_val2_name',     required: false },
      { key: 'bf_val2_practice', required: false },
      { key: 'bf_val3_name',     required: false },
      { key: 'bf_val3_practice', required: false },
      { key: 'bf_val4_name',     required: false },
      { key: 'bf_val4_practice', required: false },
      { key: 'bf_val5_name',     required: false },
      { key: 'bf_val5_practice', required: false },
      { key: 'bf_val6_name',     required: false },
      { key: 'bf_val6_practice', required: false },
    ]},
    { slug: 'content-pillars', name: 'Content Pillars', fields: [
      { key: 'bf_pillar_discover1', required: false },
      { key: 'bf_pillar_discover2', required: false },
      { key: 'bf_pillar_discover3', required: false },
      { key: 'bf_pillar1_name',     required: true },
      { key: 'bf_pillar1_sub',      required: false },
      { key: 'bf_pillar1_avatar',   required: false },
      { key: 'bf_pillar1_offer',    required: false },
      { key: 'bf_pillar1_test',     required: false },
      { key: 'bf_pillar2_name',     required: true },
      { key: 'bf_pillar2_sub',      required: false },
      { key: 'bf_pillar2_avatar',   required: false },
      { key: 'bf_pillar2_offer',    required: false },
      { key: 'bf_pillar2_test',     required: false },
      { key: 'bf_pillar3_name',     required: true },
      { key: 'bf_pillar3_sub',      required: false },
      { key: 'bf_pillar3_avatar',   required: false },
      { key: 'bf_pillar3_offer',    required: false },
      { key: 'bf_pillar3_test',     required: false },
      { key: 'bf_pillar4_name',     required: false },
      { key: 'bf_pillar4_sub',      required: false },
      { key: 'bf_pillar4_avatar',   required: false },
      { key: 'bf_pillar4_offer',    required: false },
      { key: 'bf_pillar4_test',     required: false },
      { key: 'bf_pillar5_name',     required: false },
      { key: 'bf_pillar5_sub',      required: false },
      { key: 'bf_pillar5_avatar',   required: false },
      { key: 'bf_pillar5_offer',    required: false },
      { key: 'bf_pillar5_test',     required: false },
    ]},
    { slug: 'origin-story',    name: 'Origin Story',    fields: [
      { key: 'bf_story1',       required: true },
      { key: 'bf_story2',       required: true },
      { key: 'bf_story3',       required: true },
      { key: 'bf_story4',       required: true },
      { key: 'bf_origin_story', required: false },
    ]},
    { slug: 'brand-vision',    name: 'Brand Vision',    fields: [
      { key: 'bf_vision_3yr',    required: true },
      { key: 'bf_vision_day',    required: false },
      { key: 'bf_vision_impact', required: false },
      { key: 'bf_vision_legacy', required: false },
      { key: 'bf_brand_vision',  required: false },
    ]},
  ],
  'visual-world': [
    { slug: 'overview',         name: 'Overview',         fields: [] },
    { slug: 'creator-analysis', name: 'Creator Analysis', fields: [] },
    { slug: 'color-palette',    name: 'Color Palette',    fields: [] },
    { slug: 'typography',       name: 'Typography',       fields: [] },
    { slug: 'shot-system',      name: 'Shot System',      fields: [] },
    { slug: 'visual-world-doc', name: 'Visual World Doc', fields: [] },
  ],
  'content': [
    { slug: 'overview',          name: 'Overview',          fields: [] },
    { slug: 'content-strategy',  name: 'Content Strategy',  fields: [] },
    { slug: 'sustainability',    name: 'Sustainability',     fields: [] },
    { slug: 'formats',           name: 'Formats',           fields: [] },
    { slug: 'content-system',    name: 'Content System',    fields: [] },
    { slug: 'trust-and-money',   name: 'Trust & Money',     fields: [] },
  ],
  'launch': [
    { slug: 'overview',        name: 'Overview',        fields: [] },
    { slug: 'funnel',          name: 'Funnel',          fields: [] },
    { slug: 'manychat',        name: 'ManyChat',        fields: [] },
    { slug: 'lead-magnet',     name: 'Lead Magnet',     fields: [] },
    { slug: 'bio',             name: 'Bio',             fields: [] },
    { slug: 'launch-content',  name: 'Launch Content',  fields: [] },
    { slug: 'goals',           name: 'Goals',           fields: [] },
  ],
}
