export const MODULES = [
  { slug: 'welcome',          number: '00', title: 'Welcome',                   subtitle: '' },
  { slug: 'brand-foundation', number: '01', title: 'Brand Foundation',           subtitle: 'Who You Are & What You Stand For' },
  { slug: 'visual-world',     number: '02', title: 'Define Your Visual World',   subtitle: 'Build the Aesthetic That Makes You Premium' },
  { slug: 'content',          number: '03', title: 'Create Your Content',        subtitle: 'The System That Builds Trust and Gets Customers' },
  { slug: 'launch',           number: '04', title: 'Launch',                     subtitle: 'Your Go-to-Market Strategy' },
  { slug: 'playbook',         number: '05', title: 'Your Brand Playbook',        subtitle: 'Every Answer. One Document.' },
] as const

export type ModuleSlug = typeof MODULES[number]['slug']

export interface SectionDef {
  slug: string
  name: string
  fields: { key: string; required: boolean }[]
}

// MODULE_SECTIONS defines section slugs and names for all workshop modules.
// Field arrays are populated by each module plan (02-05) when section components are built.
// welcome and playbook are excluded — they have no sub-sections.
export const MODULE_SECTIONS: Partial<Record<ModuleSlug, SectionDef[]>> = {
  'brand-foundation': [
    { slug: 'overview',        name: 'Overview',        fields: [] },
    { slug: 'brand-journey',   name: 'Brand Journey',   fields: [
      { key: 'bf_journey_outcome',   required: true },
      { key: 'bf_journey_why',       required: true },
      { key: 'bf_journey_known',     required: true },
      { key: 'bf_journey_do',        required: true },
      { key: 'bf_journey_learn',     required: true },
      { key: 'bf_journey_statement', required: false },
    ]},
    { slug: 'avatar',          name: 'Avatar',          fields: [
      { key: 'bf_av1_age',        required: false },
      { key: 'bf_av1_gender',     required: false },
      { key: 'bf_av1_occupation', required: false },
      { key: 'bf_av1_income',     required: false },
      { key: 'bf_av1_situation',  required: true },
      { key: 'bf_av1_who',        required: true },
      { key: 'bf_av1_look',       required: false },
      { key: 'bf_av1_story',      required: true },
      { key: 'bf_av1_goals',      required: true },
      { key: 'bf_av1_passions',   required: false },
      { key: 'bf_av1_struggle',   required: true },
      { key: 'bf_av1_tried',      required: false },
      { key: 'bf_av1_desired',    required: true },
      { key: 'bf_av1_fears',      required: false },
      { key: 'bf_av1_platforms',  required: false },
      { key: 'bf_av1_connection', required: false },
      { key: 'bf_av1_statement',  required: false },
      { key: 'bf_av2_age',        required: false },
      { key: 'bf_av2_gender',     required: false },
      { key: 'bf_av2_occupation', required: false },
      { key: 'bf_av2_income',     required: false },
      { key: 'bf_av2_situation',  required: false },
      { key: 'bf_av2_who',        required: false },
      { key: 'bf_av2_look',       required: false },
      { key: 'bf_av2_story',      required: false },
      { key: 'bf_av2_goals',      required: false },
      { key: 'bf_av2_passions',   required: false },
      { key: 'bf_av2_struggle',   required: false },
      { key: 'bf_av2_tried',      required: false },
      { key: 'bf_av2_desired',    required: false },
      { key: 'bf_av2_fears',      required: false },
      { key: 'bf_av2_platforms',  required: false },
      { key: 'bf_av2_connection', required: false },
      { key: 'bf_av2_statement',  required: false },
      { key: 'bf_av3_age',        required: false },
      { key: 'bf_av3_gender',     required: false },
      { key: 'bf_av3_occupation', required: false },
      { key: 'bf_av3_income',     required: false },
      { key: 'bf_av3_situation',  required: false },
      { key: 'bf_av3_who',        required: false },
      { key: 'bf_av3_look',       required: false },
      { key: 'bf_av3_story',      required: false },
      { key: 'bf_av3_goals',      required: false },
      { key: 'bf_av3_passions',   required: false },
      { key: 'bf_av3_struggle',   required: false },
      { key: 'bf_av3_tried',      required: false },
      { key: 'bf_av3_desired',    required: false },
      { key: 'bf_av3_fears',      required: false },
      { key: 'bf_av3_platforms',  required: false },
      { key: 'bf_av3_connection', required: false },
      { key: 'bf_av3_statement',  required: false },
      { key: 'bf_av4_age',        required: false },
      { key: 'bf_av4_gender',     required: false },
      { key: 'bf_av4_occupation', required: false },
      { key: 'bf_av4_income',     required: false },
      { key: 'bf_av4_situation',  required: false },
      { key: 'bf_av4_who',        required: false },
      { key: 'bf_av4_look',       required: false },
      { key: 'bf_av4_story',      required: false },
      { key: 'bf_av4_goals',      required: false },
      { key: 'bf_av4_passions',   required: false },
      { key: 'bf_av4_struggle',   required: false },
      { key: 'bf_av4_tried',      required: false },
      { key: 'bf_av4_desired',    required: false },
      { key: 'bf_av4_fears',      required: false },
      { key: 'bf_av4_platforms',  required: false },
      { key: 'bf_av4_connection', required: false },
      { key: 'bf_av4_statement',  required: false },
      { key: 'bf_av5_age',        required: false },
      { key: 'bf_av5_gender',     required: false },
      { key: 'bf_av5_occupation', required: false },
      { key: 'bf_av5_income',     required: false },
      { key: 'bf_av5_situation',  required: false },
      { key: 'bf_av5_who',        required: false },
      { key: 'bf_av5_look',       required: false },
      { key: 'bf_av5_story',      required: false },
      { key: 'bf_av5_goals',      required: false },
      { key: 'bf_av5_passions',   required: false },
      { key: 'bf_av5_struggle',   required: false },
      { key: 'bf_av5_tried',      required: false },
      { key: 'bf_av5_desired',    required: false },
      { key: 'bf_av5_fears',      required: false },
      { key: 'bf_av5_platforms',  required: false },
      { key: 'bf_av5_connection', required: false },
      { key: 'bf_av5_statement',  required: false },
    ]},
    { slug: 'core-mission',    name: 'Mission',         fields: [
      { key: 'bf_ikigai_love',    required: true },
      { key: 'bf_ikigai_good',    required: true },
      { key: 'bf_ikigai_world',   required: true },
      { key: 'bf_ikigai_paid',    required: true },
      { key: 'bf_ikigai_center',  required: false },
      { key: 'bf_mission_avatar', required: true },
      { key: 'bf_mission_outcome',required: true },
      { key: 'bf_mission_method', required: true },
      { key: 'bf_mission_why',    required: true },
      { key: 'bf_core_mission',   required: false },
    ]},
    { slug: 'core-values',     name: 'Values',          fields: [
      { key: 'bf_val1_name',     required: false },
      { key: 'bf_val1_practice', required: false },
      { key: 'bf_val2_name',     required: false },
      { key: 'bf_val2_practice', required: false },
      { key: 'bf_val3_name',     required: false },
      { key: 'bf_val3_practice', required: false },
      { key: 'bf_val4_name',     required: false },
      { key: 'bf_val4_practice', required: false },
      { key: 'bf_val5_name',     required: false },
      { key: 'bf_val5_practice', required: false },
      { key: 'bf_val6_name',     required: false },
      { key: 'bf_val6_practice', required: false },
    ]},
    { slug: 'content-pillars', name: 'Pillars',          fields: [
      { key: 'bf_pillar_discover1', required: false },
      { key: 'bf_pillar_discover2', required: false },
      { key: 'bf_pillar_discover3', required: false },
      { key: 'bf_pillar1_name',     required: true },
      { key: 'bf_pillar1_sub',      required: false },
      { key: 'bf_pillar1_avatar',   required: false },
      { key: 'bf_pillar1_offer',    required: false },
      { key: 'bf_pillar1_test',     required: false },
      { key: 'bf_pillar2_name',     required: true },
      { key: 'bf_pillar2_sub',      required: false },
      { key: 'bf_pillar2_avatar',   required: false },
      { key: 'bf_pillar2_offer',    required: false },
      { key: 'bf_pillar2_test',     required: false },
      { key: 'bf_pillar3_name',     required: true },
      { key: 'bf_pillar3_sub',      required: false },
      { key: 'bf_pillar3_avatar',   required: false },
      { key: 'bf_pillar3_offer',    required: false },
      { key: 'bf_pillar3_test',     required: false },
      { key: 'bf_pillar4_name',     required: false },
      { key: 'bf_pillar4_sub',      required: false },
      { key: 'bf_pillar4_avatar',   required: false },
      { key: 'bf_pillar4_offer',    required: false },
      { key: 'bf_pillar4_test',     required: false },
      { key: 'bf_pillar5_name',     required: false },
      { key: 'bf_pillar5_sub',      required: false },
      { key: 'bf_pillar5_avatar',   required: false },
      { key: 'bf_pillar5_offer',    required: false },
      { key: 'bf_pillar5_test',     required: false },
    ]},
    { slug: 'origin-story',    name: 'Origin Story',    fields: [
      { key: 'bf_story1',       required: true },
      { key: 'bf_story2',       required: true },
      { key: 'bf_story3',       required: true },
      { key: 'bf_story4',       required: true },
      { key: 'bf_origin_story', required: false },
    ]},
    { slug: 'brand-vision',    name: 'Brand Vision',    fields: [
      { key: 'bf_vision_3yr',    required: true },
      { key: 'bf_vision_day',    required: false },
      { key: 'bf_vision_impact', required: false },
      { key: 'bf_vision_legacy', required: false },
      { key: 'bf_brand_vision',  required: false },
    ]},
  ],
  'visual-world': [
    { slug: 'overview',         name: 'Overview',         fields: [] },
    { slug: 'creator-analysis', name: 'Creator Analysis', fields: [
      { key: 'vw_ca_creators',   required: false },
      { key: 'vw_ca_patterns',   required: false },
      { key: 'vw_ca_different',  required: false },
      { key: 'vw_ca_own',        required: false },
      { key: 'vw_ca_gap',        required: false },
    ]},
    { slug: 'mood-board',        name: 'Mood Board',       fields: [
      { key: 'vw_mb_link',       required: false },
      { key: 'vw_mb_colors',     required: false },
      { key: 'vw_mb_lighting',   required: false },
      { key: 'vw_mb_mood',       required: false },
      { key: 'vw_mb_textures',   required: false },
      { key: 'vw_mb_movie',      required: false },
      { key: 'vw_mb_time',       required: false },
      { key: 'vw_mb_place',      required: false },
    ]},
    { slug: 'color-palette',    name: 'Color Palette',    fields: [
      { key: 'vw_color_primary',   required: false },
      { key: 'vw_color_secondary', required: false },
      { key: 'vw_color_accent',    required: false },
      { key: 'vw_color_neutral',   required: false },
      { key: 'vw_color_name',      required: false },
    ]},
    { slug: 'typography',       name: 'Typography',       fields: [
      { key: 'vw_typo_primary',        required: false },
      { key: 'vw_typo_body',           required: false },
      { key: 'vw_typo_primary_italic', required: false },
      { key: 'vw_typo_primary_bold',   required: false },
      { key: 'vw_typo_body_italic',    required: false },
      { key: 'vw_typo_body_bold',      required: false },
    ]},
    { slug: 'shot-system',      name: 'Your Perspective', fields: [
      // Element 1: Setting
      { key: 'vw_shot_e1_location',    required: false },
      { key: 'vw_shot_e1_vibe',        required: false },
      { key: 'vw_shot_e1_communicate', required: false },
      { key: 'vw_shot_e1_statement',   required: false },
      // Element 2: Mood
      { key: 'vw_shot_e2_mood',        required: false },
      { key: 'vw_shot_e2_lighting',    required: false },
      { key: 'vw_shot_e2_time',        required: false },
      { key: 'vw_shot_e2_statement',   required: false },
      // Element 3: Color Language
      { key: 'vw_shot_e3_grade',       required: false },
      { key: 'vw_shot_e3_ref',         required: false },
      // Element 4: Design Details
      { key: 'vw_shot_e4_objects',     required: false },
      { key: 'vw_shot_e4_textures',    required: false },
      { key: 'vw_shot_e4_wardrobe',    required: false },
      { key: 'vw_shot_e4_never',       required: false },
    ]},
  ],
  'content': [
    // INDEX 0
    { slug: 'overview',          name: 'Overview',          fields: [] },
    // INDEX 1
    { slug: 'content-strategy',  name: 'Strategy',          fields: [
      { key: 'ct_strategy_goal',         required: false },
      { key: 'ct_strategy_next_step',    required: false },
      { key: 'ct_strategy_pain_problem', required: true  },
      { key: 'ct_strategy_unique_sol',   required: true  },
      { key: 'ct_strategy_credibility',  required: false },
    ]},
    // INDEX 2
    { slug: 'sustainability',    name: 'Sustainability',     fields: [
      // Workshop 2 — Sustainable foundation
      { key: 'ct_sustain_week_hours', required: false },
      { key: 'ct_sustain_energize',   required: false },
      { key: 'ct_sustain_drain',      required: false },
      { key: 'ct_sustain_sharp',      required: false },
      { key: 'ct_sustain_cadence',    required: true  },
      // Workshop 2 — Platform strategy
      { key: 'ct_sustain_medium',     required: false },
      { key: 'ct_sustain_audience',   required: false },
      { key: 'ct_sustain_enjoy',      required: false },
      { key: 'ct_sustain_freq',       required: false },
      { key: 'ct_sustain_platgoal',   required: false },
      { key: 'ct_sustain_primary',    required: true  },
      { key: 'ct_sustain_secondary',  required: false },
      { key: 'ct_sustain_focus',      required: false },
    ]},
    // INDEX 3
    { slug: 'batching',          name: 'Batching System',   fields: [
      // Workshop 3 — Batching System
      { key: 'ct_batch_film_day', required: false },
      { key: 'ct_batch_count',    required: false },
      { key: 'ct_batch_setup',    required: false },
      { key: 'ct_batch_commit',   required: false },
    ]},
    // INDEX 4
    { slug: 'formats',           name: 'Formats',           fields: [] },
    // INDEX 5
    { slug: 'content-system',    name: 'Content System',    fields: [] },
    // INDEX 7
    { slug: 'idea-generation',   name: 'Idea Generation',   fields: [
      // Workshop 7 — Idea Generation (pillar names)
      { key: 'ct_ig_pillar1',     required: false },
      { key: 'ct_ig_pillar2',     required: false },
      { key: 'ct_ig_pillar3',     required: false },
      { key: 'ct_ig_pillar4',     required: false },
      { key: 'ct_ig_pillar5',     required: false },
      // Workshop 7 — Idea titles (5 pillars x 4 ideas)
      { key: 'ct_ig_p1i1',        required: false },
      { key: 'ct_ig_p1i2',        required: false },
      { key: 'ct_ig_p1i3',        required: false },
      { key: 'ct_ig_p1i4',        required: false },
      { key: 'ct_ig_p2i1',        required: false },
      { key: 'ct_ig_p2i2',        required: false },
      { key: 'ct_ig_p2i3',        required: false },
      { key: 'ct_ig_p2i4',        required: false },
      { key: 'ct_ig_p3i1',        required: false },
      { key: 'ct_ig_p3i2',        required: false },
      { key: 'ct_ig_p3i3',        required: false },
      { key: 'ct_ig_p3i4',        required: false },
      { key: 'ct_ig_p4i1',        required: false },
      { key: 'ct_ig_p4i2',        required: false },
      { key: 'ct_ig_p4i3',        required: false },
      { key: 'ct_ig_p4i4',        required: false },
      { key: 'ct_ig_p5i1',        required: false },
      { key: 'ct_ig_p5i2',        required: false },
      { key: 'ct_ig_p5i3',        required: false },
      { key: 'ct_ig_p5i4',        required: false },
      // Workshop 7 — Individual angle fields (5 pillars x 4 ideas x 4 angles = 80 fields)
      ...Array.from({ length: 5 }, (_, p) =>
        Array.from({ length: 4 }, (_, i) =>
          Array.from({ length: 4 }, (_, a) =>
            ({ key: `ct_ig_p${p + 1}i${i + 1}a${a + 1}`, required: false as const })
          )
        )
      ).flat(2),
    ]},
    // INDEX 8
    { slug: 'storytelling',      name: 'Storytelling',      fields: [
      // Workshop 8 — Storytelling
      { key: 'ct_story_idea',   required: false },
      { key: 'ct_story_hook',   required: false },
      { key: 'ct_story_prob',   required: false },
      { key: 'ct_story_journey',required: false },
      { key: 'ct_story_lesson', required: false },
      { key: 'ct_story_cta',    required: false },
    ]},
    // INDEX 9
    { slug: 'starter-kit',       name: 'Starter Kit',       fields: [] },
    // INDEX 10
    { slug: 'cinematic-content', name: 'Cinematic Content', fields: [] },
  ],
  'launch': [
    { slug: 'overview',       name: 'Overview',       fields: [] },
    { slug: 'bio',            name: 'Bio',            fields: [
      // Link & Username
      { key: 'la_bio_link',          required: false },
      { key: 'la_bio_username',      required: false },
      { key: 'la_bio_ig_name',       required: false },
      // Profile Picture
      { key: 'la_bio_pfp_visibility', required: false },
      { key: 'la_bio_pfp_bg',        required: false },
      { key: 'la_bio_pfp_notes',     required: false },
      // Bio Lines
      { key: 'la_bio_line1',         required: false },
      { key: 'la_bio_line2',         required: false },
      { key: 'la_bio_line3',         required: false },
      { key: 'la_bio_line4',         required: false },
    ]},
    { slug: 'funnel',         name: 'Your Funnel',    fields: [
      // Funnel Map
      { key: 'la_funnel_platforms',       required: false },
      { key: 'la_funnel_lead_magnet',     required: false },
      { key: 'la_funnel_email_platform',  required: false },
      { key: 'la_funnel_newsletter_freq', required: false },
      { key: 'la_funnel_cta',            required: false },
      { key: 'la_funnel_offer',          required: false },
      { key: 'la_funnel_price',          required: false },
      { key: 'la_funnel_conversion',     required: false },
      // Funnel Audit
      { key: 'la_funnel_has_lm',         required: false },
      { key: 'la_funnel_has_email',      required: false },
      { key: 'la_funnel_has_offer',      required: false },
      { key: 'la_funnel_broken',         required: false },
    ]},
    { slug: 'manychat',       name: 'ManyChat & Newsletter', fields: [] },
    { slug: 'lead-magnet',    name: 'Lead Magnet',    fields: [
      { key: 'la_lm_name',         required: false },
      { key: 'la_lm_topic',        required: false },
      { key: 'la_lm_offer_bridge', required: false },
      { key: 'la_lm_format',       required: false },
      { key: 'la_lm_big_win',      required: false },
      { key: 'la_lm_outline',      required: false },
      { key: 'la_lm_cta',          required: false },
      { key: 'la_lm_tool',         required: false },
      { key: 'la_lm_delivery',     required: false },
    ]},
    { slug: 'launch-content', name: 'Launch Content', fields: [
      // Post 1 — Your Story
      { key: 'la_lc_story_why',      required: false },
      { key: 'la_lc_story_challenge',required: false },
      { key: 'la_lc_story_turning',  required: false },
      { key: 'la_lc_story_learned',  required: false },
      { key: 'la_lc_story_hook',     required: false },
      { key: 'la_lc_story_examples', required: false },
      { key: 'la_lc_story_cta',      required: false },
      // Post 2 — Positioning Deep Dive
      { key: 'la_lc_pos_belief',     required: false },
      { key: 'la_lc_pos_claim',      required: false },
      { key: 'la_lc_pos_b1',         required: false },
      { key: 'la_lc_pos_b2',         required: false },
      { key: 'la_lc_pos_b3',         required: false },
      { key: 'la_lc_pos_b4',         required: false },
      { key: 'la_lc_pos_b5',         required: false },
      { key: 'la_lc_pos_stop',       required: false },
      { key: 'la_lc_pos_oldbelief',  required: false },
      { key: 'la_lc_pos_start',      required: false },
      { key: 'la_lc_pos_newbelief',  required: false },
      { key: 'la_lc_pos_anchor',     required: false },
      // Post 3 — Authority Masterclass
      { key: 'la_lc_mc_subject',     required: false },
      { key: 'la_lc_mc_audience',    required: false },
      { key: 'la_lc_mc_authority',   required: false },
      { key: 'la_lc_mc_s1',          required: false },
      { key: 'la_lc_mc_s2',          required: false },
      { key: 'la_lc_mc_s3',          required: false },
      { key: 'la_lc_mc_s4',          required: false },
      { key: 'la_lc_mc_s5',          required: false },
      { key: 'la_lc_mc_s6',          required: false },
      { key: 'la_lc_mc_s7',          required: false },
      { key: 'la_lc_mc_hook',        required: false },
      { key: 'la_lc_mc_waterfall',   required: false },
    ]},
    { slug: 'goals',          name: 'Goals',          fields: [
      // 90-day goals
      { key: 'la_goal_content_freq',       required: false },
      { key: 'la_goal_content_platforms',  required: false },
      { key: 'la_goal_content',            required: false },
      { key: 'la_goal_followers',          required: false },
      { key: 'la_goal_email',              required: false },
      { key: 'la_goal_audience',           required: false },
      { key: 'la_goal_offer',              required: false },
      { key: 'la_goal_sales',              required: false },
      { key: 'la_goal_revenue',            required: false },
      { key: 'la_goal_system_priority',    required: false },
      { key: 'la_goal_system',             required: false },
      { key: 'la_goal_review_date',        required: false },
      { key: 'la_goal_accountability',     required: false },
    ]},
  ],
}
